package dev.rlce.kloca.runtime

/**
 * Translation table generated by the Kloca Gradle plugin for platforms, such as Wasm,
 * that do not have a native string-resource lookup API.
 */
interface KlocaTranslationResources {
    val defaultLanguage: String
    val translations: Map<String, Map<String, String>>
}
